<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ajitpawar" failures="1" tests="5" name="Test" time="38.649" errors="0" timestamp="2024-07-18T11:53:41 IST">
  <testcase classname="a.sl.testlayer.LoginPageTest" name="verifyLoginTest" time="0.074"/>
  <testcase classname="a.sl.testlayer.LogoutFunctionality" name="verifyLogoutFunctionality" time="0.626">
    <failure type="java.lang.AssertionError" message="expected [https://www.ssaucedemo.com/] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.ssaucedemo.com/] but found [https://www.saucedemo.com/]
at a.sl.testlayer.LogoutFunctionality.verifyLogoutFunctionality(LogoutFunctionality.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogoutFunctionality -->
  <testcase classname="a.sl.testlayer.ProductPageTest" name="VerifythatUsercansortProductNamefromZtoA" time="0.701"/>
  <testcase classname="a.sl.testlayer.ProductPageTest" name="VerifythatusercansortProductPricefromHightoLow" time="0.272"/>
  <testcase classname="a.sl.testlayer.ProductPageTest" name="verifyAddtoCartFunctionality" time="0.155"/>
</testsuite> <!-- Test -->
